---
# Runs on Wednesday after deps repo.
# Apply the "no ci" label to prevent cascaded CI runs on each auto-merge.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: ["deps", "no ci"]
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "01:42"

  - package-ecosystem: "docker"
    directory: "/build/docker"
    labels: ["deps", "no ci"]
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "01:42"
  - package-ecosystem: "docker"
    directory: "/build/deps"
    labels: ["deps", "no ci"]
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "01:42"

  - package-ecosystem: "gomod"
    directory: "/"
    labels: ["deps", "no ci"]
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "01:42"
  - package-ecosystem: "gomod"
    directory: "/integration"
    labels: ["deps", "no ci"]
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "01:42"
  - package-ecosystem: "gomod"
    directory: "/tools"
    labels: ["deps", "no ci"]
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "01:42"
