---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "04:42"
  - package-ecosystem: "docker"
    directory: "/"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "04:42"
  - package-ecosystem: "gomod"
    directory: "/"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "04:42"
  - package-ecosystem: "gomod"
    directory: "/tools"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "04:42"
