# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
blank_issues_enabled: false
contact_links:
  - name: General questions and discussion
    url: https://github.com/MangoDB-io/MangoDB/discussions/categories/general
    about: Please use Discussions
